# Désactiver l'accès anonyme
# allow_anonymous false
allow_anonymous true

# Chemin vers le fichier des utilisateurs
password_file /mosquitto/config/pwfile

# Réglages standards
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 1883